import * as fs from "fs";
import * as path from "path";
import { resolveConfigPath, CONFIG_FILENAME } from "./guard";

const CONFIG_TEMPLATE = `// logsguardian.config.js — generated by 'logsguardian config init'
// Edit this file to customise middleware behaviour before using other commands.
/** @type {import('logsguardian').MiddlewareOptions} */
module.exports = {
  /** 'block': send HTTP 403 on detected attacks. 'monitor': log only, never block. */
  mode: 'block',

  /** RF confidence (0-1) above which an attack-classified request is blocked.
   *  Lower = catches more attacks, more false positives. Higher = fewer false
   *  positives, more missed attacks. Default below is the calibrated value. */
  // threshold: 0.35,

  /** Model to use for inference: 'rf', 'if', or 'hybrid' (RF + anomaly detection). */
  model: 'hybrid',

  /** Fail-open timeout in ms. If inference takes longer the request is passed through. */
  timeoutMs: 50,

  /** Path to the SQLite event log. Created automatically on first run. */
  dbPath: './logsguardian.db',
};
`;

export function runConfigInit(): void {
  const configPath = resolveConfigPath();
  if (fs.existsSync(configPath)) {
    console.error(
      `logsguardian: ${CONFIG_FILENAME} already exists in ${path.dirname(configPath)}\n` +
        `Remove it first if you want to regenerate defaults.`
    );
    process.exit(1);
  }
  fs.writeFileSync(configPath, CONFIG_TEMPLATE, "utf-8");
  console.log(`Created ${configPath}`);
  console.log(`Edit ${CONFIG_FILENAME} then add the middleware to your Express app:`);
  console.log(`\n  const { logsguardian } = require('logsguardian');`);
  console.log(`  const config = require('./logsguardian.config.js');`);
  console.log(`  app.use(logsguardian(config));\n`);
}
