name: Restrict PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "PRs to main are only allowed from develop. Source branch: ${{ github.head_ref }}"
            exit 1
          fi
